#!/bin/bash
function _update_esxi(){
source ../../configs/${HOST}.conf
    echo "Output of _update_esxi :<pre>"
_ssh="ssh -o BatchMode=yes -o PasswordAuthentication=no -x -i ${_ESXI_KEY}"
echo "Start update"

    _connect="$_ssh ${_ESXI_USER}@${_ESXI_HOST}"
    _esxi="$_connect vim-cmd" 
    
            test_dir ${_TMP}/$HOST
            $_connect id > ${_TMP}/$HOST/$HOST.connect_log 2>&1
            if [[ $? -ne 0 ]]
                then
                    cat ${_TMP}/$HOST/$HOST.connect_log
                    echo "Update Error"
                    echo "</pre>"
                    _footer
                    exit 1
            fi


            date > ${_TMP}/$HOST/update_date
            $_esxi vmsvc/getallvms | grep 'vmx-'  > ${_TMP}/$HOST/$HOST.allvms

    for _VM in `$_esxi vmsvc/getallvms | egrep -v 'Vmid' | awk '{ printf $1" " }'`
        do 
            echo "Get VM $_VM ..."
            $_esxi vmsvc/get.guest $_VM > ${_TMP}/$HOST/$_VM.log

            if [[ $? -eq 0 ]]
                then
                    echo "Get $_VM Success"
                else
                    echo "Get $_VM Filed"
            fi

        done
    
    echo "Update Complete"
echo "</pre>"
}
